language: php
php:
  - 5.5
  - 5.4
  - 5.3
before_script:
 - sudo apt-get install poppler-utils
 - composer install -vvv
 - wget http://collabracam.com/resources/CollabraCam_UserGuide.pdf tests/source/test.pdf
script: 
 - phpunit tests/PdfToHtmlTest.php